name: Fetch latest Grindr version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run version fetcher script
        run: |
          python fetch_version.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add version.json
          git diff --quiet && git diff --staged --quiet || git commit -m "GR: Fetch latest Grindr version"
          git push
